name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '🚨 Tests'
    labels:
      - 'test'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$GITHUB_REPOSITORY/compare/$PREVIOUS_TAG...$LATEST_TAG
