# Plundrio configuration
# Save as ~/.plundrio.yaml or specify with --config

targetDir: /path/to/downloads
putioFolder: "plundrio"
oauthToken: "" # Use put.io OAuth token or environment variable
listenAddr: ":9091"
workerCount: 4

# Environment variables:
# PLDR_TARGETDIR, PLDR_PUTIOFOLDER, PLDR_OAUTHTOKEN
